### ISSUE TITLE
Detected addons are set to the most recent version and cannot be forced to update

### ISSUE THREAD

**Issue by khogeland** [arnauddupuis/wocli#11]
`detect` seems to assume every addon is the most recent version, because the version metadata isn't inherently available. This makes first-time use awkward, because there no way to force reinstallation. Two possible solutions:

- Don't set the version of detected addons, until `update` has been run (when you can be sure they're up-to-date)
- Allow users to force reinstallation of addons. This also means if a user's addon directories fall out of sync with the database (manual messing around, another addon manager), it can be fixed.

(By the way, thanks much for making this. Curse has such a bloated client, it no longer even runs on wine.)

**Comment by arnauddupuis** [comment]
Hi,

Thanks for the feedback, I am aware of this problem. I was also thinking to propose to reinstall all detected addons.
There is a couple of things I am doing for the 0.7.0:

- Changing DB format from CSV to JSON allowing a much cleaner handling of the local database.
- Add the `reinstall` feature. Not only for the problem you are outlining here but also because some addons have difficulties to be updated sometimes (most recently DBM).
-  Set the version to 0 if the local version is not available on detect.
- Propose to reinstall all detected addons to avoid sync issues.

What do you think about that? 

(By the way you're welcome ^^ I'm also working on a UI for all this).

Thanks for your contribution.

**Comment by khogeland** [comment]
That all sounds great and should fix the issue 👍  Would contribute if I had ever touched Perl...

**Comment by arnauddupuis** [comment]
To be honest I didn't really think about anyone but me using it, let alone contribute ;-)
I'm probably going to rewrite everything in C++/Qt for multi-platform and UI addition.

Perl's fun though ^^

**Comment by arnauddupuis** [comment]
@khogeland I implemented the reinstall command in c186acbff1e010459e62341b86bb2b6c6cc5977b.
You can now reinstall all or part of the installed addons.
I'm working on version detection in detect before marking this issue as resolved.
